Initialize components
Bishoy-Samwel/bookstore pull request #1
Opened 2021-09-08 08:14 UTC by Bishoy-Samwel

- [ ] Initialise React app.
- [ ] Add React Redux (npm install react-redux).
- [ ] Structure your application files using a "feature folder" approach and
- [ ] use the ducks pattern for your Redux files.
- [ ] The building blocks of your app should be set as re-usable components.
- [ ] Add React Router and set two <Route>sand <Link>s  for the app's navigation
- [ ] Books (Default view - will display the list of books and add/remove book functionality.)
- [ ]  Categories (Should display "Under construction" text only.)

2021-09-08 15:39 UTC, mikenath223 requested changes
Hello @Bishoy-Samwel 

You've done pretty well so far!
But for a few issues, you are almost done with this. Hang in there!


## Required Changes ♻️
_Please check the comments under the review._


Happy coding, Cheers! 🚀🚀

Do feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether it is valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-08 15:40 UTC, mikenath223 commented on README.md
> +### `yarn test`
- [ ] Kindly update the readme matching [this template](https://github.com/microverseinc/readme-template).

2021-09-08 15:41 UTC, mikenath223 commented on src/components/Books.js
> +export default function User() {
- [ ] OPTIONAL - Consider changing this function name to describe the actual functionality of the function.

2021-09-08 15:42 UTC, mikenath223 commented on src/index.js
> +  </React.StrictMode>,
- [ ] Please remove the commented code here as comments make the code untidy.

2021-09-08 15:44 UTC, mikenath223 commented
- [ ] Some commit messages aren't descriptive. Please going forward ensure all commit messages actually describe the changes made in the commit.

2021-09-09 07:37 UTC, DeliceLydia approved these changes
# Congratulations🎉 🎉 

## Hi @Bishoy-Samwel, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard).. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-09 08:13 UTC, merged